"""Generate src/data/players.ts from the Wikipedia WC2026 squads page
(download squads.html first: see README in this folder's gen-data.py)."""
import io, re, html

SECTION_TO_CODE = {
    "Czech_Republic": "CZE", "Mexico": "MEX", "South_Africa": "RSA",
    "South_Korea": "KOR", "Bosnia_and_Herzegovina": "BIH", "Canada": "CAN",
    "Qatar": "QAT", "Switzerland": "SUI", "Brazil": "BRA", "Haiti": "HAI",
    "Morocco": "MAR", "Scotland": "SCO", "Australia": "AUS",
    "Paraguay": "PAR", "Turkey": "TUR", "United_States": "USA",
    "Curaçao": "CUW", "Ecuador": "ECU", "Germany": "GER",
    "Ivory_Coast": "CIV", "Japan": "JPN", "Netherlands": "NED",
    "Sweden": "SWE", "Tunisia": "TUN", "Belgium": "BEL", "Egypt": "EGY",
    "Iran": "IRN", "New_Zealand": "NZL", "Cape_Verde": "CPV",
    "Saudi_Arabia": "KSA", "Spain": "ESP", "Uruguay": "URU",
    "France": "FRA", "Iraq": "IRQ", "Norway": "NOR", "Senegal": "SEN",
    "Algeria": "ALG", "Argentina": "ARG", "Austria": "AUT",
    "Jordan": "JOR", "Colombia": "COL", "DR_Congo": "COD",
    "Portugal": "POR", "Uzbekistan": "UZB", "Croatia": "CRO",
    "England": "ENG", "Ghana": "GHA", "Panama": "PAN",
}

s = io.open("squads.html", encoding="utf-8").read()

# split the page into team sections by h3 id
positions = []
for m in re.finditer(r'<h3 id="([^"]+)"', s):
    positions.append((m.group(1), m.start()))
positions.append(("__END__", len(s)))

ROW = re.compile(
    r'<tr class="nat-fs-player">.*?>(GK|DF|MF|FW)</a>.*?'
    r'<th data-sort-value="[^"]*" scope="row">(.*?)</th>',
    re.S,
)
TAG = re.compile(r"<[^>]+>")

out = []
for (sec, start), (_, end) in zip(positions, positions[1:]):
    code = SECTION_TO_CODE.get(sec)
    if not code:
        continue
    seg = s[start:end]
    rows = ROW.findall(seg)
    assert 23 <= len(rows) <= 27, f"{sec}: parsed {len(rows)} players"
    for pos, name_html in rows:
        name = html.unescape(TAG.sub("", name_html)).strip()
        # strip footnote markers like [a] and "(captain)" suffixes
        name = re.sub(r"\[\w+\]$", "", name).strip()
        name = re.sub(r"\s*\((?:vice-)?captain\)$", "", name, flags=re.I).strip()
        out.append((code, name, pos))

assert len({c for c, _, _ in out}) == 48, "missing teams"
print("players:", len(out))

buf = io.StringIO()
buf.write("// Generated by scripts/gen-players.py from Wikipedia: 2026 FIFA World Cup squads.\n")
buf.write("// Do not edit by hand.\n\n")
buf.write("export interface SquadPlayer {\n  name: string\n  team: string\n  pos: 'GK' | 'DF' | 'MF' | 'FW'\n}\n\n")
buf.write("export const SQUADS: SquadPlayer[] = [\n")
for code, name, pos in out:
    safe = name.replace("\\", "\\\\").replace('"', '\\"')
    buf.write(f'  {{ name: "{safe}", team: "{code}", pos: "{pos}" }},\n')
buf.write("]\n")
io.open("src/data/players.ts", "w", encoding="utf-8").write(buf.getvalue())
