"""Generate src/data/teams.ts and src/data/matches.ts from wc26.json
(fixturedownload.com feed of the official FIFA WC2026 schedule)."""
import json, io

CODES = {
    "Algeria": "ALG", "Argentina": "ARG", "Australia": "AUS", "Austria": "AUT",
    "Belgium": "BEL", "Bosnia and Herzegovina": "BIH", "Brazil": "BRA",
    "Cabo Verde": "CPV", "Canada": "CAN", "Colombia": "COL", "Congo DR": "COD",
    "Croatia": "CRO", "Curaçao": "CUW", "Czechia": "CZE",
    "Côte d'Ivoire": "CIV", "Ecuador": "ECU", "Egypt": "EGY", "England": "ENG",
    "France": "FRA", "Germany": "GER", "Ghana": "GHA", "Haiti": "HAI",
    "IR Iran": "IRN", "Iraq": "IRQ", "Japan": "JPN", "Jordan": "JOR",
    "Korea Republic": "KOR", "Mexico": "MEX", "Morocco": "MAR",
    "Netherlands": "NED", "New Zealand": "NZL", "Norway": "NOR",
    "Panama": "PAN", "Paraguay": "PAR", "Portugal": "POR", "Qatar": "QAT",
    "Saudi Arabia": "KSA", "Scotland": "SCO", "Senegal": "SEN",
    "South Africa": "RSA", "Spain": "ESP", "Sweden": "SWE",
    "Switzerland": "SUI", "Tunisia": "TUN", "Türkiye": "TUR", "USA": "USA",
    "Uruguay": "URU", "Uzbekistan": "UZB",
}
STAGE = {1: "group", 2: "group", 3: "group", 4: "r32", 5: "r16", 6: "qf", 7: "sf"}

d = json.load(open("wc26.json", encoding="utf-8"))
groups = {}
for m in d:
    if m["Group"]:
        g = m["Group"].replace("Group ", "")
        groups[m["HomeTeam"]] = g
        groups[m["AwayTeam"]] = g

assert len(groups) == 48 and all(t in CODES for t in groups), "team mapping incomplete"

out = io.StringIO()
out.write("// Generated by scripts/gen-data.py from the official WC2026 schedule\n")
out.write("// (fixturedownload.com feed). Do not edit by hand.\n\n")
out.write("export interface Team {\n  code: string\n  name: string\n  group: string\n}\n\n")
out.write("export const TEAMS: Team[] = [\n")
for name in sorted(groups, key=lambda n: (groups[n], n)):
    out.write(f'  {{ code: "{CODES[name]}", name: "{name}", group: "{groups[name]}" }},\n')
out.write("]\n\nexport const teamByCode = new Map(TEAMS.map((t) => [t.code, t]))\n")
open("src/data/teams.ts", "w", encoding="utf-8").write(out.getvalue())

out = io.StringIO()
out.write("// Generated by scripts/gen-data.py from the official WC2026 schedule\n")
out.write("// (fixturedownload.com feed). Do not edit by hand.\n\n")
out.write('export type Stage = "group" | "r32" | "r16" | "qf" | "sf" | "third_place" | "final"\n\n')
out.write("""export interface MatchInfo {
  matchNumber: number
  stage: Stage
  group: string | null
  /** Team code, or null for knockout slots until filled in by the user */
  home: string | null
  away: string | null
  /** Bracket label shown while a knockout slot is empty, e.g. "1A", "W74" */
  homeLabel: string | null
  awayLabel: string | null
  kickoffUtc: string
  venue: string
}

export const MATCHES: MatchInfo[] = [
""")
for m in sorted(d, key=lambda m: m["MatchNumber"]):
    n = m["MatchNumber"]
    stage = STAGE.get(m["RoundNumber"], "third_place" if n == 103 else "final")
    grp = f'"{m["Group"].replace("Group ", "")}"' if m["Group"] else "null"
    ko = m["DateUtc"].replace(" ", "T")
    venue = m["Location"].replace('"', '\\"')
    if m["Group"]:
        home, away = f'"{CODES[m["HomeTeam"]]}"', f'"{CODES[m["AwayTeam"]]}"'
        hl = al = "null"
    else:
        home = away = "null"
        def lab(s):
            return "null" if s == "To be announced" else f'"{s}"'
        hl, al = lab(m["HomeTeam"]), lab(m["AwayTeam"])
    out.write(
        f'  {{ matchNumber: {n}, stage: "{stage}", group: {grp}, home: {home}, away: {away}, '
        f'homeLabel: {hl}, awayLabel: {al}, kickoffUtc: "{ko}", venue: "{venue}" }},\n'
    )
out.write("]\n\nexport const matchByNumber = new Map(MATCHES.map((m) => [m.matchNumber, m]))\n")
open("src/data/matches.ts", "w", encoding="utf-8").write(out.getvalue())
print("teams:", len(groups), "matches:", len(d))
