// Generated by scripts/gen-data.py from the official WC2026 schedule
// (fixturedownload.com feed). Do not edit by hand.

export interface Team {
  code: string
  name: string
  group: string
}

export const TEAMS: Team[] = [
  { code: "CZE", name: "Czechia", group: "A" },
  { code: "KOR", name: "Korea Republic", group: "A" },
  { code: "MEX", name: "Mexico", group: "A" },
  { code: "RSA", name: "South Africa", group: "A" },
  { code: "BIH", name: "Bosnia and Herzegovina", group: "B" },
  { code: "CAN", name: "Canada", group: "B" },
  { code: "QAT", name: "Qatar", group: "B" },
  { code: "SUI", name: "Switzerland", group: "B" },
  { code: "BRA", name: "Brazil", group: "C" },
  { code: "HAI", name: "Haiti", group: "C" },
  { code: "MAR", name: "Morocco", group: "C" },
  { code: "SCO", name: "Scotland", group: "C" },
  { code: "AUS", name: "Australia", group: "D" },
  { code: "PAR", name: "Paraguay", group: "D" },
  { code: "TUR", name: "Türkiye", group: "D" },
  { code: "USA", name: "USA", group: "D" },
  { code: "CUW", name: "Curaçao", group: "E" },
  { code: "CIV", name: "Côte d'Ivoire", group: "E" },
  { code: "ECU", name: "Ecuador", group: "E" },
  { code: "GER", name: "Germany", group: "E" },
  { code: "JPN", name: "Japan", group: "F" },
  { code: "NED", name: "Netherlands", group: "F" },
  { code: "SWE", name: "Sweden", group: "F" },
  { code: "TUN", name: "Tunisia", group: "F" },
  { code: "BEL", name: "Belgium", group: "G" },
  { code: "EGY", name: "Egypt", group: "G" },
  { code: "IRN", name: "IR Iran", group: "G" },
  { code: "NZL", name: "New Zealand", group: "G" },
  { code: "CPV", name: "Cabo Verde", group: "H" },
  { code: "KSA", name: "Saudi Arabia", group: "H" },
  { code: "ESP", name: "Spain", group: "H" },
  { code: "URU", name: "Uruguay", group: "H" },
  { code: "FRA", name: "France", group: "I" },
  { code: "IRQ", name: "Iraq", group: "I" },
  { code: "NOR", name: "Norway", group: "I" },
  { code: "SEN", name: "Senegal", group: "I" },
  { code: "ALG", name: "Algeria", group: "J" },
  { code: "ARG", name: "Argentina", group: "J" },
  { code: "AUT", name: "Austria", group: "J" },
  { code: "JOR", name: "Jordan", group: "J" },
  { code: "COL", name: "Colombia", group: "K" },
  { code: "COD", name: "Congo DR", group: "K" },
  { code: "POR", name: "Portugal", group: "K" },
  { code: "UZB", name: "Uzbekistan", group: "K" },
  { code: "CRO", name: "Croatia", group: "L" },
  { code: "ENG", name: "England", group: "L" },
  { code: "GHA", name: "Ghana", group: "L" },
  { code: "PAN", name: "Panama", group: "L" },
]

export const teamByCode = new Map(TEAMS.map((t) => [t.code, t]))
